// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections;
namespace flyrpc
{
	public class Router
	{
		private Dictionary<byte, Action<object> messageHandlers;
		public Router ()
		{

		}

		public void OnMessage(byte cmd, Action<object> handler)
		{

		}
	}
}