// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
namespace flyrpc
{
	public class Router
	{
		private Dictionary<byte, Object> messageHandlers;
		public Router ()
		{
            this.messageHandlers = new Dictionary<byte, Object>();
		}

		public void AddRoute(byte cmd, object handler)
		{
            //this.messageHandlers.Add(cmd, handler);
		}
	}
}
